name: Auto Update Homepage

on:
  push:
    branches:
      - main

    paths:
      - "**"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  homepage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Homepage
        run: |
          node scripts/generate-homepage.js

      - name: Commit Updated Homepage
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update homepage"
          file_pattern: index.html
