name: Image Optimizer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Optimize PNG and JPG Images
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: "85"
          pngQuality: "85"

      - name: Commit optimized images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto optimize images"
