name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate sitemap.xml
        run: |
          BASE_URL="https://multitool.click"
          TODAY=$(date +%F)

          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          find . -name index.html | while read FILE
          do

            DIR=$(dirname "$FILE")
            DIR=${DIR#./}

            if [ "$DIR" = "." ]; then
              URL="$BASE_URL/"
              PRIORITY="1.0"
              CHANGEFREQ="daily"
            else
              URL="$BASE_URL/$DIR/"
              PRIORITY="0.8"
              CHANGEFREQ="weekly"
            fi

            echo "Adding $URL"

            cat >> sitemap.xml <<EOF
  <url>
    <loc>$URL</loc>
    <lastmod>$TODAY</lastmod>
    <changefreq>$CHANGEFREQ</changefreq>
    <priority>$PRIORITY</priority>
  </url>
EOF

          done

          echo "</urlset>" >> sitemap.xml

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add sitemap.xml

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update sitemap"
            git push
          fi
